### ISSUE TITLE
Tests will always fail without codechanges

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/bergamot-translator-tests#17]
We hide some things behind a guard here:

https://github.com/browsermt/bergamot-translator/blob/main/app/CMakeLists.txt#L7

For whatever reason. This however makes the tests fail. Since we test both the app, and the cli, at least one of the two will fail depending on what flag is set. We should *really* have a better solution than `CMakeLists.txt` manually before testing.

**Comment by jerinphilip** [comment]
I'm confused. Does the build instructions at [doc/marian-integration.md](https://github.com/browsermt/bergamot-translator/blob/main/doc/marian-integration.md) get the full set of cmdline and work?

**Comment by XapaJIaMnu** [comment]
Sorry, I didn't read that. Yes that would compile full sources, but wasn't the point of having 2 separate WASM flags, precisely that? TO have some things disabled when actually compiling to webasm and have another stuff that just switches to the wasm compatible codepath. How could we test the wasm compatible codepath if its with it the tests refuse to run?

**Comment by kpu** [comment]
Many of the tests run quickly on native right?  Why aren't these github actions?

**Comment by jerinphilip** [comment]
Anything requiring a model download is moved here to be supplied from command line. Probably doable with a download in GitHub actions, where's that intgemm dispatch with env variable by the way?

Speed tests are intensive, can't do GitHub actions.
