### ISSUE TITLE
Enable basic tests for custom bergamot-translator builds

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/bergamot-translator-tests#6]
As we have [workflow for custom build](https://github.com/browsermt/bergamot-translator/blob/main/.github/workflows/macos-custom-marian-native.yml) in [bergamot-translator](https://github.com/browsermt/bergamot-translator) repo now, it makes sense to run the [basic test](https://github.com/browsermt/bergamot-translator-tests/blob/main/tests/basic/test_bergamot_translator_app_intgemm_8bit.cpu-threads.0.sh) for these custom artifacts as well.

I followed [README](https://github.com/browsermt/bergamot-translator-tests/blob/main/README.md) and ran the tests locally using command:

`MARIAN=/path/to/marian-dev/build ./run_brt.sh '#cpu'`

The current script fails [here](https://github.com/browsermt/bergamot-translator-tests/blob/main/run_brt.sh#L52-L61) because a lot of things in this script seems to be dependent on the artifacts that are not generated for custom builds (e.g. `app/marian-decoder-new`, `app/service-cli`).

We either need a different script or update this script to test custom builds. A different script would be a better idea in my opinion.

**Comment by jerinphilip** [comment]
That line is not very important. It can be replaced with a `test -f app/bergamot-translator-app`.

**Comment by jerinphilip** [comment]
https://github.com/browsermt/bergamot-translator-tests/tree/wasm-adjustments

**Comment by jerinphilip** [comment]
The following might need adjustments (as you see, the outputs are configured to cpu instructions available). I'm not sure what is in the custom build which will change this (intgemm / simd wormhole or something). But I hope it would be consistent in terms of expected outputs. Are we still on a different script? I think we can achieve this with the same script, given the options are disabled. Many are for marian, I'm not developing for GPU, other GEMMs at this stage (and I don't think bergamot-translator will) so we can cut stuff from the script than write a new one altogether.

https://github.com/browsermt/bergamot-translator-tests/blob/533a5fa34cfdce662502455988b57891b7fc4c3a/tests/basic/test_bergamot_translator_app_intgemm_8bit.cpu-threads.0.sh#L5-L24

**Comment by abhi-agg** [comment]
> I'm not sure what is in the custom build which will change this (intgemm / simd wormhole or something)

The custom native artifacts don't require anything special to run.

> Are we still on a different script? I think we can achieve this with the same script, given the options are disabled. I think we can achieve this with the same script, given the options are disabled. Many are for marian, I'm not developing for GPU, other GEMMs at this stage (and I don't think bergamot-translator will) so we can cut stuff from the script than write a new one altogether.

If no GPU tests are required then we can edit the same script and use it. I am not sure what functionality in this script do you require for your test cases. I know what I need. We can prune this script to keep what both of us need 👍 


Btw, The command: `MARIAN=/path/to/marian-dev/build ./run_brt.sh '#cpu'` seems to be running GPU tests as well.

```
[03/01/2021 14:13:06] Using CUDA visible devices:
[03/01/2021 14:13:06] Using number of GPU devices: 1
[03/01/2021 14:13:06] Using time out: 5m
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
---------------------
Ran 0 tests in 00:00:0.000s, 0 passed, 0 skipped, 0 failed
```

**Comment by jerinphilip** [comment]
There are no GPU tests in effect, since full marian-tests are deleted. How about we settle on the "minimum edits" required to get the WASM build test functional? Let's try in the wasm-adjustments branch and PR it in once both are good. 

You can modify the scripts to suit wasm, I'll try at my end if anything in the full thing breaks and complain/fix. :-)

**Comment by abhi-agg** [comment]
`MARIAN=/path/to/marian-dev/build ./run_brt.sh '#cpu'`

Is this the right command that should be used to run tests (of course, I replaced `/path/to/marian-dev/build` with the build directory on my local machine)? I followed [this](https://github.com/browsermt/bergamot-translator/pull/44#issuecomment-786655170) as per you suggestion.

**Comment by jerinphilip** [comment]
If you're worried num GPU devices 1 in the log, it's probably a false-alarm. My argument is that, we don't need to "perfect" this and spend a lot of time here. Make non-invasive edits (we don't prune and make it only CPU, if there comes a time and need I'd want the switches to be in to easily activate gpu tests). 

You don't need '#cpu' at the moment (I don't use this) because there are no gpu tests (inside the tests folder), is what I mean. 

The following are what I use on var.

```bash
jphilip@var:~/code/bergamot-translator-test-scripts$ MARIAN=/mnt/Storage/jphilip/bergamot-temporary/ TIMEOUT=45m BRT_THREADS=48 BRT_EXPECTED_MAXTIME=500 ./run_brt.sh speed-tests/test_wngt20_per
jphilip@var:~/code/bergamot-translator-test-scripts$ MARIAN=/mnt/Storage/jphilip/bergamot-temporary/ ./run_brt.sh
```

`/mnt/Storage/jphilip/bergamot-temporary/` is the cmake build dir for my setup. Does this clarify enough?

**Comment by abhi-agg** [comment]
Added [BRT_CUSTOM](https://github.com/browsermt/bergamot-translator-tests/blob/wasm-adjustments/run_brt.sh#L38)  variable in the script which when can be enabled to test the custom artifacts.

All that is left to be done is to:

- [ ] Run only [bergamot-translator-app test](/https://github.com/browsermt/bergamot-translator-tests/blob/wasm-adjustments/tests/basic/test_bergamot_translator_app_intgemm_8bit.cpu-threads.0.sh) when BRT_CUSTOM is true
- [ ] Configure BRT_CUSTOM programmatically (e.g. via an argument to the command line of `./run_brt.sh`)

**Comment by jerinphilip** [comment]
I don't follow what you're trying to say here. Let me try to answer.

The following runs bergamot-translator-regression-test on Jenkins
```bash
. /etc/environment
make install > install.log
make clean > clean.log
mkdir -p marian-dev && tar -C marian-dev -zxvf bergamot-translator.tgz
MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 ./run_brt.sh && \
MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 TIMEOUT=15m BRT_THREADS=40 BRT_EXPECTED_MAXTIME=500 ./run_brt.sh speed-tests/test_wngt20_perf.sh 
```

Your equivalent would look as follows, given the state:
```bash
make install > install.log
make clean > clean.log
mkdir -p marian-dev && tar -C marian-dev -zxvf bergamot-translator.tgz
MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 BRT_CUSTOM=true ./run_brt.sh 

MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 ./run_brt.sh '#wasm' # For wasm runnable test
MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 ./run_brt.sh '#native' # For custom-marian
MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 ./run_brt.sh '#vanilla' # For those against full marian.


# Not required, WASM can't handle this.
# MARIAN=./marian-dev/build CUDA_VISIBLE_DEVICES=0,1 TIMEOUT=15m BRT_THREADS=40 BRT_EXPECTED_MAXTIME=500 ./run_brt.sh speed-tests/test_wngt20_perf.sh 
```

You (and me, to some extent) can use this in your local development, I don't see a point of adding wasm scripts to Jenkins@vali (additional maintainence), your browser teams should propogate error reports back anyway.

I have adjusted the tags, please look at diff. You can use tags to switch which is capable of running what.

**Comment by abhi-agg** [comment]
> I don't see a point of adding wasm scripts to Jenkins@vali (additional maintainence), your browser teams should propogate error reports back anyway.

@jerinphilip Fine by me.

A simple question. Currently, any new PR/push to main branch of [bergamot-translator](https://github.com/browsermt/bergamot-translator) repo invokes which of the following bergamot-translator-tests?
1. `#vanilla` (For full marian)
2. `#native` (For custom-marian)

**Comment by abhi-agg** [comment]
@jerinphilip and I both agreed to let Jenkins run following tests automatically for any new PR/push to `main` branch of [bergamot-translator](https://github.com/browsermt/bergamot-translator) repo

1. `#vanilla` (For full marian): This is already running
2. `#native` (For custom-marian): This will be added by @jerinphilip
